### ISSUE TITLE
qair < 1 is valid under extreme conditions

### ISSUE THREAD

**Issue by rcornes** [NOCSurfaceProcesses/AirSeaFluxCode#3]
https://github.com/NOCSurfaceProcesses/AirSeaFluxCode/blob/e054c738ee3437488b9b200532717433a0b3916c/AirSeaFluxCode/src/hum_subs.py#L380

This was originally incorporated to accomodate different units of qair. However, with this change to enforcing g/kg the nature of this check has changed to one solely related to extreme humidity values. 

Under very low temperatures (around -20C) values of qair < 1 are possible.

**Comment by jtsiddons** [comment]
This value check was added as an equivalent check to the original test that relative humidity units are % (that not all are below 1). This issue applies to both tests as both `qair` and `RH` could by affected by extreme low temperatures.

**Comment by jtsiddons** [comment]
Possibly replace raise errors with warnings and proceed with calculation under assumption that the data is valid.
